sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tLQJgvd2YnQsQKESgfd
    access-key-secret: LnAWNWsQV0C27DUslBsUTHdLY7UA6m
    bucket-name: sky-take-out-submerge
  wechat:
    appid: wxd4f16ef7fcbb645c
    secret: 7d1b66205fc25ab6efb5434824583cbf